### ISSUE TITLE
New creature

### ISSUE THREAD

**Issue by jjehl** [poppy-project/poppy-creature#23]
Do you allow me to add an externe creature like that : 
existing_creatures = ['poppy-humanoid', 'poppy-torso', 'poppy-ergo-jr', 'poppy-4dof-arm-mini', 'poppy-6dof-right-arm', 'poppy-dragster-mini', 'poppy-ergo', 'roboticia-quattro']

@pierre-rouanet I would like to use a pull, but didn't remenber that my origin is the poppy repo, so sorry I would like to ask you before. If it is a problem for you just delete my push. 
It could be really simple for me to use all the poppy services and so to add my creature in existing_creature

**Comment by pierre-rouanet** [comment]
No problem with the push 😄 

That being said I'm working on the new pypot version which will integrate poppy-creature. I think it was too complicated to understand the separation for most people.

So, you should also add it here: https://github.com/poppy-project/pypot/blob/toward-3.0/pypot/creatures/abstractcreature.py

**Comment by jjehl** [comment]
Great ! And thanks ! I agree it is better to integrate creature in pypot. I wonder if poppy-services will work fine with the name roboticia-quattro, so I want to test it before to re-do my push.
